-- with Ada.Characters.Handling;           use Ada.Characters.Handling;
with Ada.Strings.Fixed;                 use Ada.Strings.Fixed;

package body Wasabee.Colors is

   type Built_in_colors is (
     AliceBlue,
     AntiqueWhite,
     Aqua,
     Aquamarine,
     Azure,
     Beige,
     Bisque,
     Black,
     BlanchedAlmond,
     Blue,
     BlueViolet,
     Brown,
     BurlyWood,
     CadetBlue,
     Chartreuse,
     Chocolate,
     Coral,
     CornflowerBlue,
     Cornsilk,
     Crimson,
     Cyan,
     DarkBlue,
     DarkCyan,
     DarkGoldenRod,
     DarkGray,
     DarkGreen,
     DarkKhaki,
     DarkMagenta,
     DarkOliveGreen,
     DarkOrange,
     DarkOrchid,
     DarkRed,
     DarkSalmon,
     DarkSeaGreen,
     DarkSlateBlue,
     DarkSlateGray,
     DarkTurquoise,
     DarkViolet,
     DeepPink,
     DeepSkyBlue,
     DimGray,
     DodgerBlue,
     FireBrick,
     FloralWhite,
     ForestGreen,
     Fuchsia,
     Gainsboro,
     GhostWhite,
     Gold,
     GoldenRod,
     Gray,
     Green,
     GreenYellow,
     HoneyDew,
     HotPink,
     IndianRed,
     Indigo,
     Ivory,
     Khaki,
     Lavender,
     LavenderBlush,
     LawnGreen,
     LemonChiffon,
     LightBlue,
     LightCoral,
     LightCyan,
     LightGoldenRodYellow,
     LightGray,
     LightGreen,
     LightPink,
     LightSalmon,
     LightSeaGreen,
     LightSkyBlue,
     LightSlateGray,
     LightSteelBlue,
     LightYellow,
     Lime,
     LimeGreen,
     Linen,
     Magenta,
     Maroon,
     MediumAquaMarine,
     MediumBlue,
     MediumOrchid,
     MediumPurple,
     MediumSeaGreen,
     MediumSlateBlue,
     MediumSpringGreen,
     MediumTurquoise,
     MediumVioletRed,
     MidnightBlue,
     MintCream,
     MistyRose,
     Moccasin,
     NavajoWhite,
     Navy,
     OldLace,
     Olive,
     OliveDrab,
     Orange,
     OrangeRed,
     Orchid,
     PaleGoldenRod,
     PaleGreen,
     PaleTurquoise,
     PaleVioletRed,
     PapayaWhip,
     PeachPuff,
     Peru,
     Pink,
     Plum,
     PowderBlue,
     Purple,
     Red,
     RosyBrown,
     RoyalBlue,
     SaddleBrown,
     Salmon,
     SandyBrown,
     SeaGreen,
     SeaShell,
     Sienna,
     Silver,
     SkyBlue,
     SlateBlue,
     SlateGray,
     Snow,
     SpringGreen,
     SteelBlue,
     Tan,
     Teal,
     Thistle,
     Tomato,
     Turquoise,
     Violet,
     Wheat,
     White,
     WhiteSmoke,
     Yellow,
     YellowGreen);

   RGB_val: constant array(Built_in_colors) of Integer:=
   (   AliceBlue  => 16#F0F8FF#,
       AntiqueWhite  => 16#FAEBD7#,
       Aqua  => 16#00FFFF#,
       Aquamarine  => 16#7FFFD4#,
       Azure  => 16#F0FFFF#,
       Beige  => 16#F5F5DC#,
       Bisque  => 16#FFE4C4#,
       Black  => 16#000000#,
       BlanchedAlmond  => 16#FFEBCD#,
       Blue  => 16#0000FF#,
       BlueViolet  => 16#8A2BE2#,
       Brown  => 16#A52A2A#,
       BurlyWood  => 16#DEB887#,
       CadetBlue  => 16#5F9EA0#,
       Chartreuse  => 16#7FFF00#,
       Chocolate  => 16#D2691E#,
       Coral  => 16#FF7F50#,
       CornflowerBlue  => 16#6495ED#,
       Cornsilk  => 16#FFF8DC#,
       Crimson  => 16#DC143C#,
       Cyan  => 16#00FFFF#,
       DarkBlue  => 16#00008B#,
       DarkCyan  => 16#008B8B#,
       DarkGoldenRod  => 16#B8860B#,
       DarkGray  => 16#A9A9A9#,
       DarkGreen  => 16#006400#,
       DarkKhaki  => 16#BDB76B#,
       DarkMagenta  => 16#8B008B#,
       DarkOliveGreen  => 16#556B2F#,
       DarkOrange  => 16#FF8C00#,
       DarkOrchid  => 16#9932CC#,
       DarkRed  => 16#8B0000#,
       DarkSalmon  => 16#E9967A#,
       DarkSeaGreen  => 16#8FBC8F#,
       DarkSlateBlue  => 16#483D8B#,
       DarkSlateGray  => 16#2F4F4F#,
       DarkTurquoise  => 16#00CED1#,
       DarkViolet  => 16#9400D3#,
       DeepPink  => 16#FF1493#,
       DeepSkyBlue  => 16#00BFFF#,
       DimGray  => 16#696969#,
       DodgerBlue  => 16#1E90FF#,
       FireBrick  => 16#B22222#,
       FloralWhite  => 16#FFFAF0#,
       ForestGreen  => 16#228B22#,
       Fuchsia  => 16#FF00FF#,
       Gainsboro  => 16#DCDCDC#,
       GhostWhite  => 16#F8F8FF#,
       Gold  => 16#FFD700#,
       GoldenRod  => 16#DAA520#,
       Gray  => 16#808080#,
       Green  => 16#008000#,
       GreenYellow  => 16#ADFF2F#,
       HoneyDew  => 16#F0FFF0#,
       HotPink  => 16#FF69B4#,
       IndianRed   => 16#CD5C5C#,
       Indigo   => 16#4B0082#,
       Ivory  => 16#FFFFF0#,
       Khaki  => 16#F0E68C#,
       Lavender  => 16#E6E6FA#,
       LavenderBlush  => 16#FFF0F5#,
       LawnGreen  => 16#7CFC00#,
       LemonChiffon  => 16#FFFACD#,
       LightBlue  => 16#ADD8E6#,
       LightCoral  => 16#F08080#,
       LightCyan  => 16#E0FFFF#,
       LightGoldenRodYellow  => 16#FAFAD2#,
       LightGray  => 16#D3D3D3#,
       LightGreen  => 16#90EE90#,
       LightPink  => 16#FFB6C1#,
       LightSalmon  => 16#FFA07A#,
       LightSeaGreen  => 16#20B2AA#,
       LightSkyBlue  => 16#87CEFA#,
       LightSlateGray  => 16#778899#,
       LightSteelBlue  => 16#B0C4DE#,
       LightYellow  => 16#FFFFE0#,
       Lime  => 16#00FF00#,
       LimeGreen  => 16#32CD32#,
       Linen  => 16#FAF0E6#,
       Magenta  => 16#FF00FF#,
       Maroon  => 16#800000#,
       MediumAquaMarine  => 16#66CDAA#,
       MediumBlue  => 16#0000CD#,
       MediumOrchid  => 16#BA55D3#,
       MediumPurple  => 16#9370DB#,
       MediumSeaGreen  => 16#3CB371#,
       MediumSlateBlue  => 16#7B68EE#,
       MediumSpringGreen  => 16#00FA9A#,
       MediumTurquoise  => 16#48D1CC#,
       MediumVioletRed  => 16#C71585#,
       MidnightBlue  => 16#191970#,
       MintCream  => 16#F5FFFA#,
       MistyRose  => 16#FFE4E1#,
       Moccasin  => 16#FFE4B5#,
       NavajoWhite  => 16#FFDEAD#,
       Navy  => 16#000080#,
       OldLace  => 16#FDF5E6#,
       Olive  => 16#808000#,
       OliveDrab  => 16#6B8E23#,
       Orange  => 16#FFA500#,
       OrangeRed  => 16#FF4500#,
       Orchid  => 16#DA70D6#,
       PaleGoldenRod  => 16#EEE8AA#,
       PaleGreen  => 16#98FB98#,
       PaleTurquoise  => 16#AFEEEE#,
       PaleVioletRed  => 16#DB7093#,
       PapayaWhip  => 16#FFEFD5#,
       PeachPuff  => 16#FFDAB9#,
       Peru  => 16#CD853F#,
       Pink  => 16#FFC0CB#,
       Plum  => 16#DDA0DD#,
       PowderBlue  => 16#B0E0E6#,
       Purple  => 16#800080#,
       Red  => 16#FF0000#,
       RosyBrown  => 16#BC8F8F#,
       RoyalBlue  => 16#4169E1#,
       SaddleBrown  => 16#8B4513#,
       Salmon  => 16#FA8072#,
       SandyBrown  => 16#F4A460#,
       SeaGreen  => 16#2E8B57#,
       SeaShell  => 16#FFF5EE#,
       Sienna  => 16#A0522D#,
       Silver  => 16#C0C0C0#,
       SkyBlue  => 16#87CEEB#,
       SlateBlue  => 16#6A5ACD#,
       SlateGray  => 16#708090#,
       Snow  => 16#FFFAFA#,
       SpringGreen  => 16#00FF7F#,
       SteelBlue  => 16#4682B4#,
       Tan  => 16#D2B48C#,
       Teal  => 16#008080#,
       Thistle  => 16#D8BFD8#,
       Tomato  => 16#FF6347#,
       Turquoise  => 16#40E0D0#,
       Violet  => 16#EE82EE#,
       Wheat  => 16#F5DEB3#,
       White  => 16#FFFFFF#,
       WhiteSmoke  => 16#F5F5F5#,
       Yellow  => 16#FFFF00#,
       YellowGreen  => 16#9ACD32# )  ;

   type Color_composition is (RGB, RGBA, HSL, HSLA);

   function Parse_color(s: String) return Color_Code is
     b: Built_in_colors;
     par: Natural;
     cc: Color_composition;
     pragma Unreferenced (cc); -- !!
   begin
     if s = "" then
       return 0;
     end if;
     if s(s'First)='#' then
       return Integer'Value("16" & s & '#');
     end if;
     par:= Index(s,"(");
     if par > 0 then  --  something like rgb(0,0,255) each channel: 0..255 or 0%..100%
       cc:= Color_composition'Value(s(s'First..par-1));
       return 0; -- !! to do
     end if;
     b:= Built_in_colors'Value(s);
     return RGB_val(b);
   exception
     when Constraint_Error => -- unknown color name or color composition function
       return 0;
   end Parse_color;

end Wasabee.Colors;
